#threedots_sso:
#    resource: "@ThreedotsSsoBundle/Resources/config/routing.yml"
#    prefix:   /

test_engine_dashboard:
    resource: "@TestEngineDashboardBundle/Resources/config/routing.yml"
    prefix:   /

test_engine_dashboard:
    resource: "@TestEngineSsoBundle/Resources/config/routing.yml"
    prefix:   /

